# CircleCI 2.1 configuration file
# Check https://circleci.com/docs/2.0/configuration-reference/ for more details
#
# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name`
# syntax dereferences it.
#
# Define YAML anchors
.global_environment_vars: &global_environment_vars
  DEV_IMAGE_REPO: "anchore/anchore-engine-dev"
  PROD_IMAGE_REPO: "anchore/anchore-engine"
  RELEASE_BRANCHES: "0.2 0.3 0.4 0.5 0.6"
  LATEST_RELEASE_BRANCH: "0.6"
  VERBOSE: "true"
  TERM: "xterm"

.attach_workspace: &attach_workspace
  attach_workspace:
    at: /home/circleci/workspace/

.load_docker_image: &load_docker_image
  run:
    name: Load Docker image layer cache
    command: |
      docker load -i "/home/circleci/workspace/caches/${CIRCLE_SHA1}.tar" || true

.ssh_forward_port: &ssh_forward_port
  run:
    name: Forward remote-docker ports for testing
    command: |
      ssh -MS anchore-api -fN4 -L 8228:localhost:8228 remote-docker
      ssh -MS k8s-api -fN4 -L 32768:localhost:32768 remote-docker

.docker_login: &docker_login
  run:
    name: Login to DockerHub
    command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

.filter_rc_tags: &filter_rc_tags
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+(\.[0-9]+)*-rc[0-9]+$/

.filter_rebuild_tags: &filter_rebuild_tags
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+(\.[0-9]+)*-r[0-9]+$/

.filter_release_branch: &filter_release_branch
  branches:
    only: 
      - /^[0-9]+(\.[0-9]+)$/
      - master
      - /^ci-.*/

.filter_semver_tags: &filter_semver_tags
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+(\.[0-9]+)*$/

# Start circleci configuration
version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.6.5
commands:
  run_tests:
    description: |
      Uses make script to run tests
      Saves the tox cache & stores log output as artifacts
    parameters:
      test_type:
        type: string
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: make test-<< parameters.test_type >>
      - save_cache:
          paths:
            - ~/project/.tox
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - store_test_results:
          path: .tox/results

jobs:
  unit_tests:
    docker:
      - image: circleci/python:3.6
    environment: *global_environment_vars
    steps:
      - checkout
      - run_tests:
          test_type: unit

  integration_tests:
    docker:
      - image: circleci/python:3.6
      - image: anchore/test-infra-minio:latest
        command:
          - server
          - /data
      - image: anchore/test-infra-swift:latest
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_PASSWORD: "postgres"
    resource_class: large
    environment:
      <<: *global_environment_vars
      ANCHORE_TEST_S3_ACCESS_KEY: "9EB92C7W61YPFQ6QLDOU"
      ANCHORE_TEST_S3_SECRET_KEY: "TuHo2UbBx+amD3YiCeidy+R3q82MPTPiyd+dlW+s"
      ANCHORE_TEST_S3_URL: "http://localhost:9000"
      ANCHORE_TEST_S3_BUCKET: "testarchivebucket"

      ANCHORE_TEST_SWIFT_AUTH_URL: "http://localhost:8080/auth/v1.0"
      ANCHORE_TEST_SWIFT_KEY: "testing"
      ANCHORE_TEST_SWIFT_USER: "test:tester"
      ANCHORE_TEST_SWIFT_CONTAINER: "testarchive"

      ANCHORE_TEST_DB_URL: "postgresql+pg8000://postgres@localhost:5432/circle_test"
      ANCHORE_TEST_DB_USER: "postgres"
      ANCHORE_TEST_DB_PASS: "postgres"
      ANCHORE_TEST_DATA_ENV_DIR: "test/data/test_data_env"
    steps:
      - checkout
      - run_tests:
          test_type: integration

  build:
    docker:
      - image: circleci/python:3.6
    resource_class: large
    environment: *global_environment_vars
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker image
          command: make build
      - run:
          name: Save image to workspace
          command: |
            rm -rf /home/circleci/workspace/caches/
            mkdir -p /home/circleci/workspace/caches/
            docker save -o "/home/circleci/workspace/caches/${CIRCLE_SHA1}.tar" ${CIRCLE_PROJECT_REPONAME}:dev
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*

  functional_tests:
    docker:
      - image: circleci/python:3.6
    resource_class: large
    environment: *global_environment_vars
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - <<: *load_docker_image
      - <<: *ssh_forward_port
      - run_tests:
          test_type: functional

  e2e_tests:
    docker:
      - image: circleci/python:3.6
    resource_class: large
    environment: *global_environment_vars
    steps:
      - setup_remote_docker
      - checkout
      - <<: *ssh_forward_port
      - <<: *docker_login
      - run:
          name: Run e2e tests
          command: make test-e2e

  push_image:
    description: Uses make script to push images to DockerHub - dev, rc, prod
    parameters:
      make_job:
        type: string
    docker:
      - image: circleci/python:3.6
    environment: *global_environment_vars
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - <<: *load_docker_image
      - <<: *docker_login
      - run:
          name: Push to Dockerhub
          command: make << parameters.make_job >>

workflows:
  default_workflow:
    jobs:
      - unit_tests
      - integration_tests
      - build
      - functional_tests:
          requires:
            - build
      - push_image:
          name: push_dev_image
          make_job: push-dev
          context: dockerhub
          filters: *filter_release_branch
          requires:
            - functional_tests
            - unit_tests
            - integration_tests
      - e2e_tests:
          context: e2e-testing
          filters: *filter_release_branch
          requires:
            - push_dev_image

  rc_image_workflow:
    jobs:
      - e2e_tests:
          name: rc_e2e_tests
          context: e2e-testing
          filters: *filter_rc_tags
      - push_image:
          name: push_rc_image
          make_job: push-rc
          context: dockerhub
          filters: *filter_rc_tags
          requires:
            - rc_e2e_tests

  prod_image_workflow:
    jobs:
      - e2e_tests:
          name: prod_e2e_tests
          context: e2e-testing
          filters: *filter_semver_tags
      - hold_for_approval:
          type: approval
          filters: *filter_semver_tags
          requires:
            - prod_e2e_tests
      - push_image:
          name: push_prod_image
          make_job: push-prod
          context: dockerhub-prod
          filters: *filter_semver_tags
          requires:
            - hold_for_approval

  rebuild_release_workflow:
    jobs:
      - unit_tests:
          filters: *filter_rebuild_tags
      - integration_tests:
          filters: *filter_rebuild_tags
      - build:
          filters: *filter_rebuild_tags
      - functional_tests:
          filters: *filter_rebuild_tags
          requires:
            - build
      - push_image:
          name: push_dev_image
          make_job: push-dev
          context: dockerhub
          filters: *filter_rebuild_tags
          requires:
            - functional_tests
            - unit_tests
            - integration_tests
      - e2e_tests:
          context: e2e-testing
          filters: *filter_rebuild_tags
          requires:
            - push_dev_image
      - hold_for_approval:
          type: approval
          filters: *filter_semver_tags
          requires:
            - e2e_tests
      - push_image:
          name: push_prod_image
          make_job: push-prod
          context: dockerhub-prod
          filters: *filter_semver_tags
          requires:
            - hold_for_approval